# Generated by Django 6.0.7 on 2026-07-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='last_names',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Photo',
            new_name='photo',
        ),
    ]
